export{ crearDeck } from './crear-deck.js'
export { valorCarta } from './valor-carta.js'
export { pedirCarta } from './pedir-carta.js'
export { turnoComputadora } from './turno-computadora.js'
export { crearCartaHTML } from './crear-carta.js'